# default values are commented out

# address = "127.0.0.1"
# port = 8080

# mountpoints for which disk usage is displayed
watch-mountpoints = ["/"]

# command-timeout = "10s"

[commands]
cat = ["cat", "main.go"]
date = ["date"]
rm = ["rm", "/tmp/dashboard"]
# by default commands are executed wthout shell
touch = ["sh", "-c", "date > /tmp/dashboard"]
sleep = ["sh", "-c", "while true; do sleep 1s; echo ok; done"]
